### ISSUE TITLE
Morpheus Compiling

### ISSUE THREAD

**Issue by TylerKirby** [Alatius/latin-macronizer#1]
Functions set to return an integer value are wrongly set to `return;` rather than `return 0;`.

Return statements were corrected and line 98 of smk2beta.c was changed to `if( *s == L'�' && ! fromsmk ) {`, but two errors still occurred.

Here is the error log when the original source is ran on Ubuntu 14.04: https://gist.github.com/kylepjohnson/4700056226790716dd79

**Comment by Alatius** [comment]
Hm, the log you posted indicates that flex is not installed. With it, the original source should compile, (albeit with warnings.)

**Comment by TylerKirby** [comment]
Ah, ok. With flew installed, I'm receiving the following warnings/error after running `make` in `morpheus/src`:

``` bash
cd greeklib; /Applications/Xcode.app/Contents/Developer/usr/bin/make greeklib.a
gcc -O2 -I../includes   -c -o Fclose.o Fclose.c
Fclose.c:5:1: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
xFclose(FILE *f)
^
Fclose.c:9:3: error: non-void function 'xFclose' should return a value
      [-Wreturn-type]
                return;
                ^
Fclose.c:14:1: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
xFree(char *p, char *errmess)
^
Fclose.c:28:2: warning: implicit declaration of function 'free' is invalid in
      C99 [-Wimplicit-function-declaration]
        free(p);
        ^
3 warnings and 1 error generated.
make[1]: *** [Fclose.o] Error 1
make: *** [all] Error 2
```

Note that this is on OS X. I'll talk to Kyle (manager of the CLTK) about installing flex and see if he has similar errors on Ubuntu.

**Comment by TylerKirby** [comment]
So here's what we got with flex [installed](https://gist.github.com/kylepjohnson/925f26d05fe095e3eb14). We're pretty sure this is correct, but could you confirm?

**Comment by Alatius** [comment]
Yeah, it looks the same as what I get, as far as I can tell. To test that it really works, you can start it with MORPHLIB=stemlib bin/cruncher -L and then check whether it parses Latin words as it should. (Cf. the [installation instructions](https://github.com/Alatius/latin-macronizer/blob/master/INSTALL.txt) for the macronizer.)
I'm sorry I have no experience compiling Morpheus under OS X, so I can't help with that. Possibly you can take that issue upstream?

**Comment by Alatius** [comment]
I think this is sorted out?
