### ISSUE TITLE
Question about macrons.txt

### ISSUE THREAD

**Issue by thiagotps** [Alatius/latin-macronizer#17]
Hi. I would like to know how are the words organised in this file. I have noticed that in the first column
are the non macronized words and in the last column is the macronized version. Furthermore, the second column
shows information about case, number, and type of the word. What are the possible combinations of letters in this
column and their meanings ? Finally, what is the purpose of the third column and what is the license of this file ?

**Comment by Alatius** [comment]
Hello! I have documented the format of the tags in the second column in https://cl.lingfil.uu.se/exarb/arch/winge2015.pdf, table 2.1 (on p. 8). Let me know if you have further questions, and I will be happy to help you. :-) The third column lists the lemmas, i.e. the base form, which would be listed in a dictionary. License is the same as for the whole project, GPL-3.0.
