### ISSUE TITLE
Morpheus build errors except on Ubuntu 20

### ISSUE THREAD

**Issue by Myrmex** [Alatius/latin-macronizer#22]
Hi,
in the context of a wider research project, I'm trying to wrap the functionality of this excellent macronizer in a very simple web API, and package it into a Docker image. This would allow any developer compose a stack where this simple API gets called by upper-layer services, thus providing a maybe sub-optimal, but certainly easy and flexible way of integrating it, whatever the programming language and environment. Of course, should I get it working it will be open source and publicly available.

So, my first step was following the instructions to setup the macronizer on a Linux machine. To start clean, I created a new Ubuntu VM and followed the instructions. Yet, I found out that the morpheus `make` command seems to work only on Ubuntu 20.04. There, I could follow the instructions to the end, and then write and test the API successfully. Yet, when I tried with Ubuntu 21 and 22, and in a Debian GNU/Linux 11 based distribution, I found a constant compile error at `morpheus/src` `make`:

```txt
...
a - mkend.o
a - nextsufftab.o
a - retrends.o
a - stor.o
ranlib gkends.a
gcc -o buildword expwordmain.o acccompos.o checkforbreath.o contract.o countendtables.o endindex.o euphend.o expendtable.o fixeta.o getcurrend.o indexendtables.o lcontr.o merge.o mkend.o nextsufftab.o retrends.o stor.o  gkends.a ../morphlib/morphlib.a ../greeklib/greeklib.a
/usr/bin/ld: indexendtables.o:(.bss+0x78): multiple definition of `endlines'; countendtables.o:(.bss+0x78): first defined here
/usr/bin/ld: indexendtables.o:(.bss+0x0): multiple definition of `Gstr'; countendtables.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:42: buildword] Error 1
make[1]: Leaving directory '/usr/local/macronizer/latin-macronizer/morpheus/src/gkends'
make: *** [makefile:4: all] Error 2
```

Building a Docker image implies having PostgreSql available; so I'd typically start from the [official PostgreSql Docker image](https://hub.docker.com/_/postgres). Yet, if I work with bash inside a container based on this image (in turn based on Debian GNU/Linux 11), I get the exact same compilation errors at `make` for morpheus I got on a full-fledged Ubuntu VM (when its version is different from 20.04). In all my tests, I managed to get this compiled only on a full Ubuntu 20.04 distribution, which of course is not what we start with when building a Docker image.
So, do you know of any environmental constraints for your instructions, or I'm just missing something more obvious?
Thank you!

**Comment by Alatius** [comment]
Hi, thanks for the report! I can't test this right now, but my guess is that these distributions have different versions of gcc. Cf. https://stackoverflow.com/questions/69908418/multiple-definition-of-first-defined-here-on-gcc-10-2-1-but-not-gcc-8-3-0
As a start, I would try to add "-fcommon" to the CFLAGS in the makefiles, especially in gkends/makefile, but maybe in the other ones as well.

**Comment by Myrmex** [comment]
Thank you for your quick reply! I've edited all the makefiles adding `-fcommon`, but this was not enough. I had also to comment `gk_string Gstr;` at line 6 of `countendtables.c`. This removed compile errors.

**Comment by Myrmex** [comment]
Hi, thank you again for your reply. I have now completed the wrapping procedure: [here are the results](https://github.com/Myrmex/alatius-macronizer-api.git).

**Comment by UserProgrammer** [comment]
> Hi, thanks for the report! I can't test this right now, but my guess is that these distributions have different versions of gcc. Cf. https://stackoverflow.com/questions/69908418/multiple-definition-of-first-defined-here-on-gcc-10-2-1-but-not-gcc-8-3-0 As a start, I would try to add "-fcommon" to the CFLAGS in the makefiles, especially in gkends/makefile, but maybe in the other ones as well.

This worked for me, thanks
