### ISSUE TITLE
macronizing the genitive of "unus nauta" adjectives

### ISSUE THREAD

**Issue by polycrates** [Alatius/latin-macronizer#4]
I'm working with your macronizer to produce xml versions of Vergil and Ovid's hexameters with scansion.  The macronizer is a really great piece of work - thanks!  (I tried all 3 backends for cltk's macronizer, with limited success).  I'll probably be able to give more feedback later, but for now I note that it's consistently macronizing the i in the genitive of adjectives like unus and ipse (result is ūnīus, ipsīus, should be ūnius, ipsius).  Let me know if you'd like more examples.

**Comment by Alatius** [comment]
Hi! Sorry for the late reply! As you may have seen, the macronizer is now able to produce ūnius etc. in poetry. I will leave ūnīus as the default in prose. Is this okay? I have today also added ipsius as a valid poetic variant. I had accidentally left it out earlier.
