### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rl1234567890** [Alatius/latin-macronizer#5]
Hi,

First, thank you for a very useful tool. I successfully installed it on my machine. However, I had to move latin-macronizer from my user space to /usr/local and change recursively ownership to root.root for it to work. Maybe there are  more elegant solutions, although I like it this way now. 

Cheers!

**Comment by Alatius** [comment]
Thanks for the feedback! What Linux distribution are you using?

**Comment by rl1234567890** [comment]
I'm using Linux Mint 18.1, but the same occurs on my laptop running  Ubuntu 16.10.

**Comment by Alatius** [comment]
Hm, it seems that the read access to the home dir depends on whether it is encrypted or not (understandably). In any case, it is probably a good idea to install in /usr/local/ anyway. I have updated the installation instructions to reflect this.
