### ISSUE TITLE
The macronizer is not actually compatible with Python 3

### ISSUE THREAD

**Issue by Simon-Will** [Alatius/latin-macronizer#9]
Commit 919fddb introduced Python 3 compatibility, but it was broken again by adding a string prefixed with `ur` (unicode and raw) [in macronizer.py](https://github.com/Alatius/latin-macronizer/blob/fc8eb31/macronizer.py#L820). I propose importing `unicode_literals` from `__future__` and removing the `u` prefix everywhere. I will send a pull request shortly.

**Comment by Simon-Will** [comment]
I opened the pull request #10 for this.

**Comment by Alatius** [comment]
Thank you very much!
